#
# This file is part of pysmi software.
#
# Copyright (c) 2015-2019, Ilya Etingof <etingof@gmail.com>
# License: https://github.com/pysnmp/pysmi/blob/main/LICENSE.rst
#
"""The frame every page is written into, and how a distribution replaces it.

A downstream distribution publishes this site beside its own documentation and
wants it to look like the rest of that documentation. Forking the generator to
change a header is the outcome to avoid, so the frame is data: a
:py:class:`Theme` carries the page template and the stylesheet, and a manifest
names files that replace either.

:py:class:`string.Template` rather than a template engine, because PySMI's
runtime dependencies are ``ply`` and ``requests`` and a page frame is not a
reason for a third. ``$name`` substitution is all a frame needs, and
``safe_substitute`` means an unknown placeholder in an overridden template
renders as itself rather than raising in the middle of a 5,500-page build.

See pysnmp/pysmi#276.
"""

import os
import string
from typing import Final, NamedTuple

from pysmi import error

#: The placeholders a page template may use.
#:
#: ``head`` is where the crawl metadata a distribution build asks for goes --
#: see pysnmp/pysmi#284 -- and is empty otherwise.
PLACEHOLDERS: Final[tuple[str, ...]] = (
    "title",
    "head",
    "root",
    "stylesheet",
    "heading",
    "breadcrumb",
    "content",
    "corpus",
    "generator",
)

#: The default page template -- one file, no scripts, nothing fetched. Every
#: fact the page states is in the bytes the server sent, which is what
#: pysnmp/pysmi#284 requires of it.
PAGE: Final = """\
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>$title</title>
<link rel="stylesheet" href="$stylesheet">
$head</head>
<body>
<header class="site">
<a class="home" href="${root}browse/">$corpus</a>
<nav class="breadcrumb">$breadcrumb</nav>
</header>
<main>
<h1>$heading</h1>
$content</main>
<footer class="site">
<p>Generated by $generator.</p>
</footer>
</body>
</html>
"""

#: The default stylesheet -- deliberately small and unopinionated. It sets
#: type, spacing and table rules and nothing else, so a distribution replacing
#: it is replacing a page's appearance rather than fighting one.
#:
#: No web fonts and no external anything -- a page that fetches a stylesheet
#: from a third party is a page that renders differently once that third party
#: is unreachable, and a corpus is published to be durable.
STYLESHEET: Final = """\
:root {
  color-scheme: light dark;
  --ink: #1a1a1a;
  --dim: #595959;
  --rule: #d4d4d4;
  --ground: #ffffff;
  --raised: #f6f6f6;
  --accent: #0b5fa5;
}

@media (prefers-color-scheme: dark) {
  :root {
    --ink: #e8e8e8;
    --dim: #a0a0a0;
    --rule: #3a3a3a;
    --ground: #16181a;
    --raised: #1f2225;
    --accent: #6fb3ec;
  }
}

* { box-sizing: border-box; }

body {
  margin: 0;
  background: var(--ground);
  color: var(--ink);
  font: 16px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
        "Helvetica Neue", Arial, sans-serif;
}

a { color: var(--accent); }

header.site, footer.site, main {
  max-width: 62rem;
  margin: 0 auto;
  padding: 1rem 1.25rem;
}

header.site {
  display: flex;
  flex-wrap: wrap;
  gap: 0.75rem 1.5rem;
  align-items: baseline;
  border-bottom: 1px solid var(--rule);
}

header.site .home { font-weight: 600; text-decoration: none; }

nav.breadcrumb, nav.keys { font-size: 0.875rem; color: var(--dim); }
nav.breadcrumb a::after { content: " /"; color: var(--rule); }
nav.breadcrumb a:last-child::after { content: ""; }

footer.site {
  border-top: 1px solid var(--rule);
  color: var(--dim);
  font-size: 0.8125rem;
}

h1 { font-size: 1.6rem; margin: 0 0 0.25rem; overflow-wrap: anywhere; }
h2 { font-size: 1.15rem; margin: 2rem 0 0.5rem; }
h3 { font-size: 1rem; margin: 1.5rem 0 0.35rem; }

code, .oid, pre { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
code, .oid { font-size: 0.9em; overflow-wrap: anywhere; }

pre {
  background: var(--raised);
  border: 1px solid var(--rule);
  border-radius: 4px;
  padding: 0.75rem;
  overflow-x: auto;
  font-size: 0.8125rem;
}

dl.facts { display: grid; grid-template-columns: max-content 1fr; gap: 0.3rem 1.25rem; margin: 0.75rem 0; }
dl.facts dt { color: var(--dim); }
dl.facts dd { margin: 0; overflow-wrap: anywhere; }

table { border-collapse: collapse; width: 100%; margin: 0.75rem 0; font-size: 0.9375rem; }
th, td { text-align: left; vertical-align: top; padding: 0.35rem 0.6rem 0.35rem 0; border-bottom: 1px solid var(--rule); }
th { color: var(--dim); font-weight: 600; white-space: nowrap; }

.wide { overflow-x: auto; }

ul.plain, ul.keys { list-style: none; padding: 0; margin: 0.5rem 0; }
ul.plain li { padding: 0.15rem 0; }

ul.keys { display: flex; flex-wrap: wrap; gap: 0.35rem 0.6rem; }
ul.keys li { font-size: 0.8125rem; }
ul.keys .here { font-weight: 600; }

section > :last-child { margin-bottom: 0; }
.note { color: var(--dim); font-size: 0.9375rem; }

.defs td { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.9em; overflow-wrap: anywhere; }
.defs td:first-child { white-space: nowrap; }
.defs td:last-child, .defs.typed td:nth-child(4) { font-family: inherit; font-size: inherit; }
.defs .desc { font-family: inherit; color: var(--dim); font-size: 0.875rem; overflow-wrap: normal; }

:target { background: var(--raised); }

@media (max-width: 32rem) {
  dl.facts { grid-template-columns: 1fr; gap: 0.1rem; }
  dl.facts dt { margin-top: 0.5rem; }
}
"""


class Theme(NamedTuple):
    """The page frame and the stylesheet a build renders with."""

    #: The page template, with :py:data:`~pysmi.corpus.site.theme.PLACEHOLDERS`
    #: in it.
    page: str = PAGE

    #: The stylesheet, written once at the site root.
    stylesheet: str = STYLESHEET

    #: What the header calls this corpus.
    corpus: str = "MIB corpus"

    def render(self, **fields: str) -> str:
        """One page, the frame filled in.

        Unknown placeholders survive rather than raising: an overridden
        template with a typo in it should produce a page with ``$oops`` on it,
        which somebody will see, rather than stopping a build 3,000 pages in.
        """
        return string.Template(self.page).safe_substitute(
            {"corpus": self.corpus, **fields}
        )


def load_theme(
    page: "str | None" = None,
    stylesheet: "str | None" = None,
    corpus: "str | None" = None,
) -> Theme:
    """A theme, with either file replaced by one the manifest names.

    Args:
        page: a file holding a replacement page template, or ``None`` for the
            built-in one.
        stylesheet: a file holding a replacement stylesheet, likewise.
        corpus: what the header calls this corpus.

    Returns:
        The theme.

    Raises:
        PySmiError: a named file could not be read. A theme that silently fell
            back to the default would publish a whole site in the wrong skin
            and say nothing.
    """
    return Theme(
        page=_read(page, "page template") if page else PAGE,
        stylesheet=_read(stylesheet, "stylesheet") if stylesheet else STYLESHEET,
        corpus=corpus or "MIB corpus",
    )


def _read(path: str, what: str) -> str:
    """One theme file, or a failure that names it."""
    try:
        with open(path, encoding="utf-8") as fileObj:
            return fileObj.read()

    except OSError as exc:
        raise error.PySmiError(
            f"cannot read the {what} at {os.path.abspath(path)}: {exc}"
        ) from exc
